version: '3'
services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./sql/initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    -ports:
      - 5432:5432
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    command: /bin/sh -c "cargo watch -x run"
  server:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data:
