version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: /bin/sh -c "cargo watch -x run"
  server:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
