version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.49.0
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
workflows:
  build:
    jobs:
      - build
